test1: Test passed, expected TypeError-Callee is not a function object
test2: Test passed, expected TypeError-Callee is not a function object
test3: Test passed, expected TypeError-Callee is not a function object
test4: Test passed, expected no exception thrown
test5: Test passed, expected TypeError-Callee is not a function object
test6: Test passed, expected ReferenceError-Blah is not defined
test7: Test passed, expected TypeError-Callee is not a function object
test8: Test passed, expected no exception thrown
test9: Test passed, expected no exception thrown
Passed
